name: Deploy Supabase
on:
  push:
    branches: [ "main" ]

jobs:
  supabase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Supabase CLI
        run: |
          curl -sL https://github.com/supabase/cli/releases/latest/download/supabase_$(uname -s | tr '[:upper:]' '[:lower:]')_amd64.tar.gz           | tar -xz
          sudo mv supabase /usr/local/bin/supabase

      - name: Login & Link
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          echo "$SUPABASE_ACCESS_TOKEN" | supabase login --token -
          supabase link --project-ref "$SUPABASE_PROJECT_REF"

      - name: Push migrations
        run: supabase db push

      - name: Set function secrets
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          supabase secrets set SUPABASE_URL="$SUPABASE_URL" SUPABASE_SERVICE_ROLE_KEY="$SUPABASE_SERVICE_ROLE_KEY"

      - name: Deploy edge functions
        run: supabase functions deploy payments-webhook
